# Generated by Django 3.1.7 on 2021-06-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0002_batch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='location',
        ),
    ]
