# Generated by Django 3.1.7 on 2021-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0004_batch_mass_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='txid_funding',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
