# Generated by Django 3.1.7 on 2021-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0005_location_txid_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pubkey',
            field=models.CharField(blank=True, default='', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='raddress',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
    ]
