# Generated by Django 3.1.7 on 2022-08-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0101_remove_post_is_clean'),
        ('apiRegistry', '0006_auto_20210909_1018'),
    ]

    operations = [
    ]
